[package]
name = "procplan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13"
bytemuck = "1.16.1"
iyes_perf_ui = "0.2.3"
rand = "0.8.5"
